postgresql:
    image: theearl/initdb
    container_name: pgsql
    ports:
     - "5433:5432"
    
project:
    build: .
    volumes_from:
        - postgresql
    links:
        - postgresql
   
rest:
    build: ./RESTapi
    volumes_from:
        - postgresql
    links:
        - postgresql
   